apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq-test
  labels:
    pod-security.kubernetes.io/enforce: baseline
---
apiVersion: v1
kind: Secret
metadata:
  name: regsecret
  namespace: rabbitmq-test
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K